name: CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # application.yml 파일 생성
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      # application-secret.yml 파일 생성
      - run: touch ./src/main/resources/application-secret.yml
      - run: echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml

      # 생성된 파일들을 아티팩트로 업로드
      - uses: actions/upload-artifact@v3
        with:
          name: application-files
          path: |
            ./src/main/resources/application.yml
            ./src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      # 배포용 패키지 경로 설정
      - name: Set artifact path
        run: |
          artifact=$(ls ./build/libs/*.jar | head -n 1)
          echo "artifact=$artifact" >> $GITHUB_ENV

      # 그린 환경에 배포
      - name: Deploy to Green Environment
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Flowday-web
          environment_name: Flowday-web-env-1
          version_label: github-action-${{ steps.current-time.outputs.time }}
          region: ap-northeast-2
          deployment_package: ${{ env.artifact }}

      # 블루 환경에 배포
      - name: Deploy to Blue Environment
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Flowday-web
          environment_name: Flowday-web-env
          version_label: github-action-${{ steps.current-time.outputs.time }}
          region: ap-northeast-2
          deployment_package: ${{ env.artifact }}
          use_existing_version_if_available: true

